# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sergio Ibarra-Espinosa
email: zergioibarra@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a postdoc in atmospheric scioences. I developed some R packages, 
  included VEIN https://www.geosci-model-dev.net/11/2209/2018/

baseurl: "/superblog" # the subpath of your site, e.g. /blog
url: "https://ibarraespinosa.github.io/superblog/" # the base hostname & protocol for your site
twitter_username: SergioIbarraEs1
github_username:  ibarraespinosa

# Build settings
markdown: kramdown
